/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhatito
 */
public class FormKendaraaan extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = config.koneksidb.getKoneksi();
    /**
     * Creates new form FormMotor
     */
    public FormKendaraaan() {
        initComponents();
        judul();
        tampilData();
        setLocationRelativeTo(null);
//        combo();
    }
    
    public void reset() {
        Tnoplat.setText("");
        Tkendaraan.setText("");
        Tnorangka.setText("");
        Ttipe.setText("");
        cboMerek.setSelectedItem("--Pilih--");
        Bsave.setEnabled(true);
        Bedit.setEnabled(true);
        Bdelete.setEnabled(true);
        Tnoplat.setEnabled(true);
    }
        
    public void judul() {
        Object[] judul = {"NO PLAT", "NO RANGKA", "TIPE ", "JENIS KENDARAAN","MEREK KENDARAAN"};
        tabModel = new DefaultTableModel(null, judul);
        TBmotor.setModel(tabModel);
    }
    
    public void tampilData(){
        try {
           st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("select * from motor");
            while (rs.next()) {
                Object[] data = {
                   rs.getString("no_plat"),
                   rs.getString("no_rangka"),
                   rs.getString("tipe"),
                   rs.getString("jenis"),
                   rs.getString("merk")
                };
                tabModel.addRow(data);
            }
        } catch (Exception e) {
          e.printStackTrace();  
        }
        reset();
    }
//    public void combo(){
//    try{
//        Connection cn = config.koneksidb.getKoneksi();
//        rs = st.executeQuery("select * from jenis");
//        
//        while(rs.next()){
//            cmbkendaraan.addItem(rs.getString("jenis_kendaraan"));
//        } 
//        rs.close(); cn.close();
//        
//    }catch(Exception e){
//        JOptionPane.showMessageDialog(rootPane, e);
//    }
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tnorangka = new javax.swing.JTextField();
        Bcari = new javax.swing.JButton();
        Ttipe = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBmotor = new javax.swing.JTable();
        Bsave = new javax.swing.JButton();
        Bedit = new javax.swing.JButton();
        Bdelete = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        Bkeluar = new javax.swing.JButton();
        Tnoplat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tkendaraan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboMerek = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel1.setText("DATA KENDARAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 430, -1));

        jLabel3.setText("No Plat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel4.setText("Tipe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel10.setText("No Rangka");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        Tnorangka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnorangkaActionPerformed(evt);
            }
        });
        getContentPane().add(Tnorangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, -1));

        Bcari.setText("Cari");
        Bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcariActionPerformed(evt);
            }
        });
        getContentPane().add(Bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 60, -1));

        Ttipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtipeActionPerformed(evt);
            }
        });
        getContentPane().add(Ttipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 220, 30));

        TBmotor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBmotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBmotorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBmotor);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 550, 210));

        Bsave.setText("Simpan");
        Bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaveActionPerformed(evt);
            }
        });
        getContentPane().add(Bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 90, -1));

        Bedit.setText("Update");
        Bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeditActionPerformed(evt);
            }
        });
        getContentPane().add(Bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 90, -1));

        Bdelete.setText("Delete");
        Bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 90, -1));

        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });
        getContentPane().add(Breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 80, -1));

        Bkeluar.setText("Keluar");
        Bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 80, -1));

        Tnoplat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnoplatActionPerformed(evt);
            }
        });
        getContentPane().add(Tnoplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, -1));

        jLabel2.setText("Jenis Kendaraan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Tkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TkendaraanActionPerformed(evt);
            }
        });
        getContentPane().add(Tkendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 220, -1));

        jLabel5.setText("Merk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        cboMerek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Honda", "Yamaha", "Suzuki", " " }));
        getContentPane().add(cboMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBmotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBmotorMouseClicked
        try {
            Tnoplat.setText(tabModel.getValueAt(TBmotor.getSelectedRow(), 0).toString());
            Tnorangka.setText(tabModel.getValueAt(TBmotor.getSelectedRow(), 1).toString());
            Ttipe.setText(tabModel.getValueAt(TBmotor.getSelectedRow(), 2).toString());
            Tkendaraan.setText(tabModel.getValueAt(TBmotor.getSelectedRow(), 3).toString());
            cboMerek.setSelectedItem(tabModel.getValueAt(TBmotor.getSelectedRow(), 4).toString()); 
            //cmbkendaraan.setSelectedItem(TBmotor);
            Bsave.setEnabled(false);
            Bedit.setEnabled(true);
            Bdelete.setEnabled(true);
            Tnoplat.setEnabled(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_TBmotorMouseClicked

    private void TnorangkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnorangkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnorangkaActionPerformed

    private void TtipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtipeActionPerformed

    private void BeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeditActionPerformed
       
            try {
                st = cn.createStatement();
                st.executeUpdate("UPDATE motor set no_rangka='"
                    +Tnorangka.getText()
                    + "', tipe='"+Ttipe.getText()
                    + "', merk='"+cboMerek.getSelectedItem()
                    + "' WHERE no_plat='"+ Tnoplat.getText()+"'");
                JOptionPane.showMessageDialog(null, "Berhasil Diupdate");
                tampilData();
                reset();
            } catch (Exception e) {
                e.printStackTrace();
            
        }
    }//GEN-LAST:event_BeditActionPerformed

    private void BdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdeleteActionPerformed
        int jawab;
        if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin Menghapus Data?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            try {
                st = cn.createStatement();
                st.executeUpdate("delete from motor where no_plat='" + Tnoplat.getText()+ "'");
                JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
                tampilData();
                reset();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_BdeleteActionPerformed

    private void BkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkeluarActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BkeluarActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        reset();
    }//GEN-LAST:event_BresetActionPerformed

    private void BsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaveActionPerformed
       
           PreparedStatement ps=null;
    String sql="Insert into motor values(?,?,?,?,?)";
    try{
        if ((Tnoplat.getText().equals("")) 
          || (Tkendaraan.getText().equals("")) 
          || (Tnorangka.getText().equals("")) 
          || (Ttipe.getText().equals(""))
          || (cboMerek.getSelectedItem().equals("--Pilih--")))
          
        {
            JOptionPane.showMessageDialog(rootPane,"Lengkapi data dengan benar terlebih dahulu!"); 
        }
        else
        {
        ps=config.koneksidb.getKoneksi().prepareStatement(sql);
        ps.setString(1,Tnoplat.getText());
         ps.setString(2,Tkendaraan.getText());
        ps.setString(3,Tnorangka.getText());
         ps.setString(4,Ttipe.getText());
        ps.setString(5,(String)cboMerek.getSelectedItem());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Data Anda Sudah Disimpan!"); 
        tampilData();
                reset();
        }
    }catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"No plat ini sudah ada, silahkan masukkan No plat yang baru" );
    }
    }//GEN-LAST:event_BsaveActionPerformed

    private void BcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcariActionPerformed
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM motor where no_plat ='"+
                Tnoplat.getText()+"'");
            while (rs.next()){

                Tnorangka.setText(rs.getString(2));
                Ttipe.setText(rs.getString(3));
                JOptionPane.showMessageDialog(rootPane, "Ini Datanya Berdasarkan ID Customer = '"+Tnoplat.getText()+"' ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "eror"+e);
        }
    }//GEN-LAST:event_BcariActionPerformed

    private void TnoplatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnoplatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnoplatActionPerformed

    private void TkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TkendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TkendaraanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKendaraaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcari;
    private javax.swing.JButton Bdelete;
    private javax.swing.JButton Bedit;
    private javax.swing.JButton Bkeluar;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Bsave;
    private javax.swing.JTable TBmotor;
    private javax.swing.JTextField Tkendaraan;
    private javax.swing.JTextField Tnoplat;
    private javax.swing.JTextField Tnorangka;
    private javax.swing.JTextField Ttipe;
    private javax.swing.JComboBox<String> cboMerek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
