/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Bhatito
 */
public final class FormService extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = config.koneksidb.getKoneksi();
    DecimalFormat df = new DecimalFormat("##,###,###.-");
    double biaya;
    /**
     * Creates new form FormService
     */
    public FormService() {
        initComponents(); 
        judul();
        tampilData();
        nofaktur();
        setLocationRelativeTo(null);
        Tnoservice.setText(String.valueOf(nofaktur()));
        Tnoservice.setEditable(false);
        Tnama.setEditable(false);
        Tnorangka.setEditable(false);
        Tjenis.setEditable(false);
        Tkendaraan.setEditable(false);
        Tmerek.setEditable(false);
    }
    
    private int nofaktur() {
        String noAwal = null;
        int noSekarang = 0;
        try {
            String sql = "SELECT MAX(no_service) AS sekarang FROM service";
            rs = st.executeQuery(sql);
            if (rs.next()) {
                noAwal = rs.getString("sekarang");
            }

            if (noAwal == null) {
                noSekarang = 1;
            } else {
                noSekarang = Integer.valueOf(noAwal) + 1;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return noSekarang;
    }
    
   
    public void judul() {
        Object[] judul = {"NO SERVICE", "TANGGAL", "ID CUSTOMER", "NAMA CUSTOMER", "NO PLAT", "JENIS KENDARAAN","NO RANGKA ","TIPE"," MERK ", "BIAYA"};
        tabModel = new DefaultTableModel(null, judul);
        TBservice.setModel(tabModel);
    }
    
        public void tampilData(){
        try {
            
           st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT service.no_service, service.tgl_service, customer.id_customer, customer.nama, motor.no_plat, motor.no_rangka, motor.tipe, motor.jenis, motor.merk, service.biaya FROM service JOIN customer ON service.id_customer = customer.id_customer JOIN motor ON service.no_plat = motor.no_plat");
            while (rs.next()) {
                Object[] data = {
                   rs.getString("service.no_service"),
                   rs.getString("service.tgl_service"),
                   rs.getString("customer.id_customer"),
                   rs.getString("customer.nama"),
                   rs.getString("motor.no_plat"),
                   rs.getString("motor.tipe"),
                   rs.getString("motor.no_rangka"),
                   rs.getString("motor.jenis"),
                   rs.getString("motor.merk"),
                   rs.getString("service.biaya")
                };
                tabModel.addRow(data);
            }
        } catch (Exception e) {
          e.printStackTrace();  
        }
        reset();
    }
    
    public void reset() {
        Tidcustomer.setText("");
        Tnoplat.setText("");
        Tnoplat.setText("");
        Tnorangka.setText("");
        Tjenis.setText("");
        Tnama.setText("");
        Tkendaraan.setText("");
        Tbiaya.setText("");
        Tmerek.setText("");
        Tidcustomer.setEnabled(true);
        Tnoplat.setEnabled(true);
        Tnoservice.setText(String.valueOf(nofaktur()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tidcustomer = new javax.swing.JTextField();
        Bcari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBservice = new javax.swing.JTable();
        Bsave = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        Bkeluar = new javax.swing.JButton();
        Tnoservice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tnoplat = new javax.swing.JTextField();
        Tbiaya = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Tnama = new javax.swing.JTextField();
        Tnorangka = new javax.swing.JTextField();
        Tjenis = new javax.swing.JTextField();
        Bcari1 = new javax.swing.JButton();
        DTtgl = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        Tkendaraan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Tmerek = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setText("DATA SERVICE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setText("No Service");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jLabel4.setText("Biaya Service");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 20));

        jLabel10.setText("ID Customer");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        Tidcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(Tidcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, -1));

        Bcari.setText("Cari");
        Bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcariActionPerformed(evt);
            }
        });
        getContentPane().add(Bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 60, -1));

        TBservice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBserviceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBservice);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 870, 280));

        Bsave.setText("Simpan");
        Bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaveActionPerformed(evt);
            }
        });
        getContentPane().add(Bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, -1));

        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });
        getContentPane().add(Breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 100, -1));

        Bkeluar.setText("Keluar");
        Bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 90, -1));
        getContentPane().add(Tnoservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, -1));

        jLabel5.setText("Nama Customer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 20));

        jLabel6.setText("Tgl Service");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel7.setText("No Plat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        Tnoplat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnoplatActionPerformed(evt);
            }
        });
        getContentPane().add(Tnoplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, -1));

        Tbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbiayaActionPerformed(evt);
            }
        });
        getContentPane().add(Tbiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 220, -1));

        jLabel8.setText("Jenis");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel9.setText("No Rangka");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        Tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnamaActionPerformed(evt);
            }
        });
        getContentPane().add(Tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 220, -1));

        Tnorangka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnorangkaActionPerformed(evt);
            }
        });
        getContentPane().add(Tnorangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 220, -1));

        Tjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TjenisActionPerformed(evt);
            }
        });
        getContentPane().add(Tjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 220, -1));

        Bcari1.setText("Cari");
        Bcari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bcari1ActionPerformed(evt);
            }
        });
        getContentPane().add(Bcari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 60, -1));
        getContentPane().add(DTtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel2.setText("Tipe");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        getContentPane().add(Tkendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 220, -1));

        jLabel11.setText("Merk");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(Tmerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TidcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidcustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TidcustomerActionPerformed

    private void BcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcariActionPerformed
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM motor where no_plat ='"+
                Tnoplat.getText()+"'");
            while (rs.next()){
                Tnorangka.setText(rs.getString(2));
                Tjenis.setText(rs.getString(3));
                Tkendaraan.setText(rs.getString(4));
                Tmerek.setText(rs.getString(5));

                JOptionPane.showMessageDialog(rootPane, "Ini Datanya Berdasarkan ID Customer = '"+Tidcustomer.getText()+"' ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "eror"+e);
        }
    }//GEN-LAST:event_BcariActionPerformed

    private void TBserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBserviceMouseClicked
        try {
            Tnoservice.setText(tabModel.getValueAt(TBservice.getSelectedRow(), 0).toString());
            Tidcustomer.setText(tabModel.getValueAt(TBservice.getSelectedRow(), 1).toString());
            Tbiaya.setText(tabModel.getValueAt(TBservice.getSelectedRow(), 2).toString());
            Bsave.setEnabled(false);
            Tnoservice.setEnabled(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_TBserviceMouseClicked

    private void BsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaveActionPerformed
        if (Tnoservice.getText().isEmpty() || Tidcustomer.getText().isEmpty() || Tbiaya.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data!");
        } else {          
         try {
              st = cn.createStatement();
              st.executeUpdate("INSERT INTO service VALUES('"+
                      Tnoservice.getText()+"','"+
                      Tidcustomer.getText()+"','"+
                      Tnoplat.getText()+"','"+
                      new SimpleDateFormat("yyyy-MM-dd").format(DTtgl.getDate())+"','"+
                      Tbiaya.getText()+"')");
                JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
                tampilData();
                reset();
          } catch (Exception e) {
              System.out.println("customer gagal reservasi service kendaraan : " + e);
          }
      }
    }//GEN-LAST:event_BsaveActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        reset();
    }//GEN-LAST:event_BresetActionPerformed

    private void BkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkeluarActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BkeluarActionPerformed

    private void TnoplatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnoplatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnoplatActionPerformed

    private void TbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbiayaActionPerformed

    private void TnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnamaActionPerformed

    private void TnorangkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnorangkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnorangkaActionPerformed

    private void TjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TjenisActionPerformed

    private void Bcari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bcari1ActionPerformed
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM customer where id_customer ='"+
                Tidcustomer.getText()+"'");
            while (rs.next()){
                Tnama.setText(rs.getString(2));

                
                JOptionPane.showMessageDialog(rootPane, "Ini Datanya Berdasarkan ID Customer = '"+Tidcustomer.getText()+"' ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "eror"+e);
        }
    }//GEN-LAST:event_Bcari1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcari;
    private javax.swing.JButton Bcari1;
    private javax.swing.JButton Bkeluar;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Bsave;
    private com.toedter.calendar.JDateChooser DTtgl;
    private javax.swing.JTable TBservice;
    private javax.swing.JTextField Tbiaya;
    private javax.swing.JTextField Tidcustomer;
    private javax.swing.JTextField Tjenis;
    private javax.swing.JTextField Tkendaraan;
    private javax.swing.JTextField Tmerek;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Tnoplat;
    private javax.swing.JTextField Tnorangka;
    private javax.swing.JTextField Tnoservice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
